### ISSUE TITLE
Initiatives List - Sort

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#3]
AS a user
IN ORDER TO can select different sorts formats 
NEED TO be able to select the view  order by: random, recent, more signatures or more comments

**Comment by jsperezg** [comment]
Category filter is not shown. The reason is that usually categories are created by an administrator for a participatory space. An initiative is a participatory space itself. IMHO it has no sense to allow the user to create a random category for each initiative created in the system. Instead the initiative type should be used the same way that categories are used for other participatory spaces.

Pending tasks:

* Write tests.
* Implement a selector that allows multiple categories selected but using as source the initiative types.

**Comment by jsperezg** [comment]
Needs validation

**Comment by arnaumonty** [comment]
It makes sense. We don't need categories for each initiative because we just have one initiative and we don't need to categorize it in order to filter. The initiative types should be the attribution in order to navigate in the initiative page list.

**Comment by jsperezg** [comment]
Can we close this issue?
