### ISSUE TITLE
Why those rake tasks?

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-initiatives#47]
Why are those rake tasks included with this repo? Are they intended to aid with local development, or are they intended for production use? Are they intended to be run every day in a cron?

Please move the code to services so they can be easily called from other places, and change all rake tasks to jobs using the [ActiveJob interface](http://edgeguides.rubyonrails.org/active_job_basics.html). 

If they are intended to be run every day in a cron, please provide a way for this to happen, and provide docs.

**Comment by josepjaume** [comment]
To be specific, these are the tasks @mrcasals is talking about:

https://github.com/decidim/decidim-initiatives#rake-tasks

I believe they could all be triggered via buttons in the admin interface (after turning them into services).

**Comment by jsperezg** [comment]
This tasks will run in a cron because they perform periodic checks. Active Job do not allow to creating recurrent jobs.

With regards to how to integrate this jobs, whenever gem do not works inside an isolated engine. This is something that each implementation must decide: 

* Install whenever gem in the app and let it manage the execution of these rake tasks.
* System operator creates the cron jobs by hand.

The only thing I see that could be improved is the docs informing the potential users that this three rake tasks must run every day.

@josepjaume IMHO, force a system administrator to enter the gui to press a button each and every day of his whole life while this task can be performed automatically by a cron is not an option. :)
