### ISSUE TITLE
Do not save user data in the clear

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-initiatives#52]
As per Decidim's [social contract](https://decidim.org/contract/), we cannot save user data in the clear. The `create_initiative_extra_data.rb` seems to be saving user data in the clear:

- Document ID
- Address (street, city, province, postal code)
- Phone number

For organizations, it's saving:

- Document ID
- Address (only street, it seems)

We might need input from @decidim/product for this, as I might be misunderstanding the use case here just in case.

**Comment by jsperezg** [comment]
This has been implemented this offer the users the possibility of printing the forms that Barcelona Council requires to accept an initiative.

**Comment by xabier** [comment]
@jsperezg is right, we should not store this data but just to generate a form that needs to be printed latter

**Comment by xabier** [comment]
Sorry @jsperezg and @mrcasals my previous message was too criptic.

You are both right :) 

This issue was discussed in length out of github, on previous sprint planning meetings. I don't know about how it is implemented on the code but the idea is that we need just to store temporarily this data, we need not store it or keep it on the DDBB, and it is only needed to fill a form, that the user can latter print and send it to physically to City-council registry.

**Comment by mrcasals** [comment]
Data is currently being stored in the database in the clear. In order to print the form, maybe we should, in order:

1. Save the user data in the database, but hashed so we cannot decrypt it ([just like we do in the verifications, for example](https://github.com/AjuntamentdeBarcelona/decidim-barcelona/blob/4724d9ca8bbb84ece517f23deb8572c2277fc3d6/app/services/census_authorization_handler.rb#L46-L50))
1. When the user wants to print the form, ask for the same data
1. If the data is correct, generate a PDF that the user can download. We should not persist this PDF in the server side.
1. If the data is incorrect, ask again.

This would prevent us from saving data in the clear in the database. By asking the data again, we are ensuring the user is who they say they are, and we are getting the data again from the user to generate the PDF. The only problem would be the address, as street names are not standardized. Maybe we could not save the street name, actually (so it's a fake input), and use the value of the last form to generate the PDF?

That's just a suggestion, I'll leave how to solve this to you. I just wanted to point out that right now this is breaking the Decidim social contract as data is saved in the clear.

**Comment by xabier** [comment]
Thanks for your input @mrcasals . Actually, I am going to ask something much simpler at this stage @jsperezg 

* Remove the extra fields required on the Wizard
* Return the empty forms that participants need to fill for the iniciative (@arnaumonty will provide you with more information)

This way we don't store anything right now, if this is an obstacle to activate this functionality at decidim.barcelona.

Here is the scenario:
1. We need to activate the Iniciatives ASAP.
2. We don't see how we can, in the near future, connect Decidim to the official registry of city council, so we don't really need the data to be processed any time soon (although we might need this in the future). Citizens can simply print the forms (empty) and fill the data themselves before submitting them to a citizen office.
3. When we know how to operate as a bridge between Decidim front-end and city-council's official digital registry, we might need to keep this information to deliver it, but right now we don't know how.

Sorry we could not foresee these problems in detail when planning the module.

**Comment by arnaumonty** [comment]
Hi, attending that the step to add personal data is configurable, we can leave it unchecked by default or we can eliminate the step on the wizard. Maybe the first option is better, but I understand that this has other implications in order to be integrated.

The solution of @mrcasals seems good to me. Just in case we activate the validation step on wizard proposal creation we should hash the information, but we don't have to print it in the pdf. Actually, the print version of pdf is a temporary solution. @jsperezg thoughts?

**Comment by jsperezg** [comment]
I'm working right now in a patch that implements Xabier suggestions.
