### ISSUE TITLE
Could not run tests in my dev machine

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-initiatives#62]
I couldn't run the tests locally, and as per #40 we cannot know if the tests actually pass.

I think this is due to the component dependencies not being up to date.

**Comment by jsperezg** [comment]
I'm able to run all specs locally. THe thing is that the current decidim dummy app is prepared for an engine that lives inside of the core so I had to made some changes to it in order to execute the tests.

IMHO we can do a couple of things:

1. As an exceptional measure, add to the repo the decidim dummy app.
2. Document the changes and create a new rake task in the core that creates a dummy app for an engine that lives outside the core.

After 2 is finished and tested decidim dummy app should be removed from the repo.

**Comment by mrcasals** [comment]
We have `rake decidim:generate_external_test_app` but for some reason it failed when I tried to run it in this repo 😞  Something about missing bootsnap (a gem we removed in master)

**Comment by jsperezg** [comment]
In my case it finishes with this error

home/jsperezg/Dropbox/Desarrollo/ASPGems/decidim/barcelona/decidim-initiatives/spec/decidim_dummy_app/Gemfile not found

This issue is blocking. Without this it has no sense to proceed with circle ci integration and thus #50 can't be closed as well

**Comment by jsperezg** [comment]
I will open an issue in Decidim's core informing about this problem.

**Comment by mrcasals** [comment]
As reported in https://github.com/decidim/decidim/issues/2301, the issue is this repo is depending on old versions of `decidim`. Please update the dependency version to `0.7.4` (note that we are about to release `0.8.0` early next week, so you'll need to bump the version there too).

This will also unlock #40.

**Comment by jsperezg** [comment]
Using rails instead of rake fixed the issues in my case.
